- name: Install NGINX
  import_tasks: install.yml

- name: Configure NGINX
  import_tasks: config.yml

- name: Remove VirtualHosts
  import_tasks: remove_vhosts.yml

- name: Deploy VirtualHosts
  import_tasks: add_vhosts.yml

- name: Configure firewall
  import_tasks: firewall.yml

- name: Start NGINX
  import_tasks: start.yml
