- name: Install NGINX
  import_tasks: install.yml

- name: Configure NGINX
  import_tasks: config.yml

- name: Deploy VirtualHosts
  include_tasks: add_vhosts.yml
  with_items: "{{ vhosts }}"
  loop_control:
    loop_var: item

- name: Remove VirtualHosts
  include_tasks: remove_vhosts.yml
  with_items: "{{ removed_vhosts }}"
  loop_control:
    loop_var: item

- name: Configure firewall
  import_tasks: firewall.yml
