Vagrant.configure("2") do |config|
  config.vm.box = "marcinbojko/rockylinux9_arm64"

  config.vm.provider "parallels" do |prl|
    # Customize the amount of memory on the VM:
    prl.memory = "1024"
  end

  # Désactive les updates auto qui peuvent ralentir le lancement de la machine
  config.vm.box_check_update = false

  # La ligne suivante permet de désactiver le montage d'un dossier partagé (ne marche pas tout le temps directement suivant vos OS, versions d'OS, etc.)
  config.vm.synced_folder ".", "/vagrant", disabled: true

  # Exécution d'un script au démarrage de la VM
  config.vm.provision "shell", path: "setup.sh"
end
