---
- name: Open port 80
  firewalld:
    port: 80/tcp
    state: enabled
    permanent: yes
  become: yes
  notify:
    - Restart NGINX

- name: Open port 443
  firewalld:
    port: 443/tcp
    state: enabled
    permanent: yes
  become: yes
  notify:
    - Restart NGINX
