- name: Create users
  ansible.builtin.user:
    name: "{{ item.name }}"
    password: "{{ item.password }}"
    groups: "wheel, {{ item.group }}"
    shell: "{{ item.shell }}"
    home: "/home/{{ item.name }}"
    state: present
  with_items: "{{ users|default([]) }}"

- name: Add public ssh key to authorized_keys
  authorized_key:
    user: "{{ item.name }}"
    state: present
    key: "{{ lookup('file', 'files/'+ item.name + '.key.pub') }}"
  with_items: "{{ users|default([]) }}"
